-- MySQL Script generated by MySQL Workbench
-- jue 28 may 2020 18:26:48 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TravelHut
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TravelHut` ;

-- -----------------------------------------------------
-- Schema TravelHut
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TravelHut` DEFAULT CHARACTER SET utf8 ;
USE `TravelHut` ;

-- -----------------------------------------------------
-- Table `TravelHut`.`CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TravelHut`.`CLIENTE` ;

CREATE TABLE IF NOT EXISTS `TravelHut`.`CLIENTE` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `antiguedad` DATE NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `telefono_UNIQUE` (`telefono` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelHut`.`RESERVA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TravelHut`.`RESERVA` ;

CREATE TABLE IF NOT EXISTS `TravelHut`.`RESERVA` (
  `codigo_reserva` INT NOT NULL AUTO_INCREMENT,
  `importe` INT NOT NULL,
  `idCliente` INT NOT NULL,
  `fecha_reserva` DATE NOT NULL,
  `fecha_viaje` DATE NOT NULL,
  `venta_concretada` TINYINT(1) NOT NULL,
  PRIMARY KEY (`codigo_reserva`),
  INDEX `fk_RESERVA_CLIENTE1_idx` (`idCliente` ASC),
  CONSTRAINT `fk_RESERVA_CLIENTE1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `TravelHut`.`CLIENTE` (`idCliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelHut`.`CONVENIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TravelHut`.`CONVENIO` ;

CREATE TABLE IF NOT EXISTS `TravelHut`.`CONVENIO` (
  `codigo_convenio` INT NOT NULL AUTO_INCREMENT,
  `importe` INT NOT NULL,
  `codigo_reserva` INT NOT NULL,
  PRIMARY KEY (`codigo_convenio`),
  INDEX `fk_CONVENIO_RESERVA1_idx` (`codigo_reserva` ASC),
  UNIQUE INDEX `codigo-reserva_UNIQUE` (`codigo_reserva` ASC),
  CONSTRAINT `fk_CONVENIO_RESERVA1`
    FOREIGN KEY (`codigo_reserva`)
    REFERENCES `TravelHut`.`RESERVA` (`codigo_reserva`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelHut`.`TRANSPORTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TravelHut`.`TRANSPORTE` ;

CREATE TABLE IF NOT EXISTS `TravelHut`.`TRANSPORTE` (
  `codigo_convenio` INT NOT NULL,
  `idTransporte` INT NOT NULL,
  `compania` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `precio` INT NOT NULL,
  PRIMARY KEY (`codigo_convenio`),
  UNIQUE INDEX `idTransporte_UNIQUE` (`idTransporte` ASC),
  CONSTRAINT `fk_TRANSPORTE_CONVENIO1`
    FOREIGN KEY (`codigo_convenio`)
    REFERENCES `TravelHut`.`CONVENIO` (`codigo_convenio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelHut`.`ALOJAMIENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TravelHut`.`ALOJAMIENTO` ;

CREATE TABLE IF NOT EXISTS `TravelHut`.`ALOJAMIENTO` (
  `codigo_convenio` INT NOT NULL,
  `nombre_aloj` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `cant_noches` INT NOT NULL,
  `precio` INT NOT NULL,
  PRIMARY KEY (`codigo_convenio`),
  CONSTRAINT `fk_ALOJAMIENTO_CONVENIO1`
    FOREIGN KEY (`codigo_convenio`)
    REFERENCES `TravelHut`.`CONVENIO` (`codigo_convenio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelHut`.`DESTINO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TravelHut`.`DESTINO` ;

CREATE TABLE IF NOT EXISTS `TravelHut`.`DESTINO` (
  `nombre_dest` VARCHAR(45) NOT NULL,
  `continente` VARCHAR(45) NOT NULL,
  `popularidad` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre_dest`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelHut`.`GUIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TravelHut`.`GUIA` ;

CREATE TABLE IF NOT EXISTS `TravelHut`.`GUIA` (
  `idGuia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `nombre_dest` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGuia`),
  INDEX `fk_GUIA_DESTINO1_idx` (`nombre_dest` ASC),
  UNIQUE INDEX `telefono_UNIQUE` (`telefono` ASC),
  CONSTRAINT `fk_GUIA_DESTINO1`
    FOREIGN KEY (`nombre_dest`)
    REFERENCES `TravelHut`.`DESTINO` (`nombre_dest`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelHut`.`ACTIVIDAD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TravelHut`.`ACTIVIDAD` ;

CREATE TABLE IF NOT EXISTS `TravelHut`.`ACTIVIDAD` (
  `nombre_actividad` VARCHAR(45) NOT NULL,
  `nombre_dest` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre_actividad`),
  INDEX `fk_ACTIVIDAD_DESTINO1_idx` (`nombre_dest` ASC),
  CONSTRAINT `fk_ACTIVIDAD_DESTINO1`
    FOREIGN KEY (`nombre_dest`)
    REFERENCES `TravelHut`.`DESTINO` (`nombre_dest`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelHut`.`ENFERMEDAD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TravelHut`.`ENFERMEDAD` ;

CREATE TABLE IF NOT EXISTS `TravelHut`.`ENFERMEDAD` (
  `nombre_enf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre_enf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelHut`.`PRECAUCION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TravelHut`.`PRECAUCION` ;

CREATE TABLE IF NOT EXISTS `TravelHut`.`PRECAUCION` (
  `nombre_dest` VARCHAR(45) NOT NULL,
  `nombre_enf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre_dest`, `nombre_enf`),
  INDEX `fk_DESTINO_has_ENFERMEDAD_ENFERMEDAD1_idx` (`nombre_enf` ASC),
  INDEX `fk_DESTINO_has_ENFERMEDAD_DESTINO_idx` (`nombre_dest` ASC),
  CONSTRAINT `fk_DESTINO_has_ENFERMEDAD_DESTINO`
    FOREIGN KEY (`nombre_dest`)
    REFERENCES `TravelHut`.`DESTINO` (`nombre_dest`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_DESTINO_has_ENFERMEDAD_ENFERMEDAD1`
    FOREIGN KEY (`nombre_enf`)
    REFERENCES `TravelHut`.`ENFERMEDAD` (`nombre_enf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelHut`.`VISITA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TravelHut`.`VISITA` ;

CREATE TABLE IF NOT EXISTS `TravelHut`.`VISITA` (
  `nombre_dest` VARCHAR(45) NOT NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`nombre_dest`, `idCliente`),
  INDEX `fk_DESTINO_has_CLIENTE_CLIENTE1_idx` (`idCliente` ASC),
  INDEX `fk_DESTINO_has_CLIENTE_DESTINO1_idx` (`nombre_dest` ASC),
  CONSTRAINT `fk_DESTINO_has_CLIENTE_DESTINO1`
    FOREIGN KEY (`nombre_dest`)
    REFERENCES `TravelHut`.`DESTINO` (`nombre_dest`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_DESTINO_has_CLIENTE_CLIENTE1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `TravelHut`.`CLIENTE` (`idCliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelHut`.`SIMILAR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TravelHut`.`SIMILAR` ;

CREATE TABLE IF NOT EXISTS `TravelHut`.`SIMILAR` (
  `nombre_dest` VARCHAR(45) NOT NULL,
  `nombre_dest_turistico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre_dest`, `nombre_dest_turistico`),
  INDEX `fk_DESTINO_has_DESTINO_DESTINO2_idx` (`nombre_dest_turistico` ASC),
  INDEX `fk_DESTINO_has_DESTINO_DESTINO1_idx` (`nombre_dest` ASC),
  CONSTRAINT `fk_DESTINO_has_DESTINO_DESTINO1`
    FOREIGN KEY (`nombre_dest`)
    REFERENCES `TravelHut`.`DESTINO` (`nombre_dest`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_DESTINO_has_DESTINO_DESTINO2`
    FOREIGN KEY (`nombre_dest_turistico`)
    REFERENCES `TravelHut`.`DESTINO` (`nombre_dest`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelHut`.`SINTOMA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TravelHut`.`SINTOMA` ;

CREATE TABLE IF NOT EXISTS `TravelHut`.`SINTOMA` (
  `nombre_sintoma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre_sintoma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelHut`.`TIENE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TravelHut`.`TIENE` ;

CREATE TABLE IF NOT EXISTS `TravelHut`.`TIENE` (
  `nombre_sintoma` VARCHAR(45) NOT NULL,
  `nombre_enf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre_sintoma`, `nombre_enf`),
  INDEX `fk_SINTOMA_has_ENFERMEDAD_ENFERMEDAD1_idx` (`nombre_enf` ASC),
  INDEX `fk_SINTOMA_has_ENFERMEDAD_SINTOMA1_idx` (`nombre_sintoma` ASC),
  CONSTRAINT `fk_SINTOMA_has_ENFERMEDAD_SINTOMA1`
    FOREIGN KEY (`nombre_sintoma`)
    REFERENCES `TravelHut`.`SINTOMA` (`nombre_sintoma`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_SINTOMA_has_ENFERMEDAD_ENFERMEDAD1`
    FOREIGN KEY (`nombre_enf`)
    REFERENCES `TravelHut`.`ENFERMEDAD` (`nombre_enf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
